### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vgonda**
This PR

- Updates gradle to 3.2.1
- Migrates to use AndroidX named libraries over support libraries.

We potentially want to create a branch to point to in the README for pre migration for people who aren't on AndroidX yet. With what is included here, it's not much different from support library other than name, but it is still a good point. Should we add a note to the README?

### CODE REVIEW

**Review by nisrulz — APPROVED** [review]
Looks Good to me 👍

**Comment by nisrulz** [comment]
@vgonda This looks good to me. Can you do the below 2 things
1. Change the target of this PR to `develop`
1. Add a link in the readme right before the "Summary" title pointing to: https://github.com/raywenderlich/RWAndroidTutorial/tree/pre_androidx
> This is the pre-androidx branch. the link can be "Switch to pre-androidx branch"

Rest, I will make sure everything is merged and functional in `master` branch.

Thank you for putting in the effort to update this project 😺

**Comment by vgonda** [comment]
@nisrulz Thank you so much for the review! Those things should be taken care of now 😄

**Comment by mgaf** [comment]
6de4373

**Pull request merged**
