### PR TITLE
Updating and adding Copyright to Kotlin/Java files

### PR DESCRIPTION
**Pull request by fernandospr**

### CODE REVIEW

**Comment by fernandospr** [comment]
@orionthewake Please, kindly check my PR.

**Review by nisrulz — COMMENTED** [review]
Looks good to me in terms of changes added.

I am no lawyer, but I would say that the date of Copyright usually corresponds to the date of when the file was created. In that sense, the year actually should be `2018`.

@orionthewake What do you think?

**Review by nisrulz — APPROVED** [review]

**Comment by nisrulz** [comment]
I have changed the base to be `develop`. @fernandospr we send the changes to `develop` and then make another PR with all changes to `master`.

Thank you for opening this PR.

**Comment by fernandospr** [comment]
Thanks @nisrulz :] 
I changed the year because this project is used as a template for projects that will be created during `2019`.

**Comment by alienvelour** [comment]
@fernandospr @nisrulz Thanks for this! Yep agreed on 2019, and pretty soon we'll need 2020!

**Pull request merged**
